/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package member;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import rohmatcell.koneksidb;

/**
 *
 * @author arifika
 */
public class pembeliansaldomember extends javax.swing.JInternalFrame {

    /**
     * Creates new form pembeliansaldomember
     */
    public pembeliansaldomember(String user) {
        initComponents();
        idpetugas.setText(user);
        
         ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          Calendar cal = new GregorianCalendar();
        String nolTanggal = "";
        String nolBulan = "";
        String nolTahun = "";
        // Membuat Date
        Date dt = new Date();
        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
        int nilaiTanggal = cal.get(Calendar.DAY_OF_MONTH);
        int nilaiBulan = cal.get(Calendar.MONTH);
        
        int nilaiTahun = cal.get(Calendar.YEAR);
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilaiTanggal<10){
            nolTanggal="0";
        }
        if ((nilaiBulan+1)<10){
            nolBulan="0";
        }
        if (nilaiTahun<10){
            nolTahun="0";
        }
        // Membuat String JAM, MENIT, DETIK
        String tanggal = nolTanggal + Integer.toString(nilaiTanggal);
        String bulan = nolBulan + Integer.toString(nilaiBulan+1);
        String tahun = nolTahun + Integer.toString(nilaiTahun);
        // Menampilkan pada Layar
        
        tampiltanggal.setText(tahun+"-"+bulan+"-"+tanggal);
      }
    };
    // Timer
    new Timer(1000, taskPerformer).start();
  }
    public void header(){
        String username = idpetugas.getText().toString();
        String b [] = new String [3];
        try {
            Connection c = koneksidb.getkoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("select id_petugas from petugas where id_petugas = '"+username+"'");
            
            while ( r.next()){
              
            b[0]=r.getString("id_petugas");
            //b[1]=r.getString("hak_akses");
            //b[1]=r.getString("nama_pegawai");
            }
        } catch (SQLException e) {
                System.out.println("Error di select all Id Petugas! "+e);
        }
        idpetugas.setText(b[0]);
        //labelJabatan.setText(b[1]);
        //labelNama.setText(b[2]);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nominalpembelian = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tampiltanggal = new javax.swing.JLabel();
        idpetugas = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login : ");

        labelUser.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PEMBELIAN SALDO");
        setOpaque(true);

        beli.setText("Beli");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });

        jLabel1.setText("Nominal Pembelian  : ");

        nominalpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalpembelianActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PEMBELIAN SALDO");

        tampiltanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampiltanggal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tanggal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        tampiltanggal.setVerifyInputWhenFocusTarget(false);

        idpetugas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        idpetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(beli)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nominalpembelian))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tampiltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tampiltanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(idpetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nominalpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(beli)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        // TODO add your handling code here:
        String a = idpetugas.getText().toString();
        String b = tampiltanggal.getText().toString();    
        String c = nominalpembelian.getText().toString();
        
         try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate ("INSERT INTO `pembelian_saldo`(`ID_PEMBELIAN`, `NO_HP_MEMBER`, `NOMINAL_PEMBELIAN`, `TANGGAL_PEMBELIAN`)VALUES (NULL,'"+a+"','"+c+"','"+b+"')");
        statement.close();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        
    }//GEN-LAST:event_beliActionPerformed

    private void nominalpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalpembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalpembelianActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beli;
    private javax.swing.JLabel idpetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTextField nominalpembelian;
    private javax.swing.JLabel tampiltanggal;
    // End of variables declaration//GEN-END:variables
}
