/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package member;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rohmatcell.koneksidb;

/**
 *
 * @author arifika
 */
public class pulsamember extends javax.swing.JInternalFrame {
private DefaultTableModel model;
    /**
     * Creates new form pulsamember
     */
    public pulsamember() {
        initComponents();
        
        model = new DefaultTableModel();
       
        model.addColumn("Operator");
        model.addColumn("Id Pulsa");
        model.addColumn("Harga Default");
       // model.addColumn("Harga Jual");
        model.addColumn("Harga Member");
        tabelpulsa.setModel(model);
        selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpulsa = new javax.swing.JTable();
        txtoperator = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        isihargadefault = new javax.swing.JTextField();
        isiidpulsa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isihargamember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("PULSA");

        tabelpulsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Operator", "Id Pulsa", "Harga Default", "Harga Jual"
            }
        ));
        tabelpulsa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelpulsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpulsaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpulsa);

        jLabel2.setText("OPERATOR");

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        jLabel6.setText("HARGA JUAL");

        jLabel5.setText("HARGA DEFAULT  ");

        jLabel3.setText("ID PULSA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(244, 244, 244))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(isiidpulsa)
                                    .addComponent(txtoperator, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(isihargadefault)
                                    .addComponent(isihargamember, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(batal))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(isihargadefault, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(isihargamember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtoperator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(isiidpulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(batal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        txtoperator.setText("");
        isiidpulsa.setText("");
        isihargadefault.setText("");
        isihargamember.setText("");
    }//GEN-LAST:event_batalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String operator, id_pulsa, harga_default, harga_jual, harga_member ;
        operator = txtoperator .getText().trim();
        id_pulsa = isiidpulsa.getText().trim();
        harga_default = isihargadefault.getText().trim();
        harga_member = isihargamember.getText().trim();
        
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate("UPDATE  `rohmatcell`.`pulsa` SET  `operator` =  '"+operator+"',`harga_default` =  '"+harga_default+"',`harga_member` =  '"+harga_member+"'WHERE  `pulsa`.`id_pulsa` =  '"+id_pulsa+"';");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelpulsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpulsaMouseClicked
        // TODO add your handling code here:
        int row = tabelpulsa.getSelectedRow();
        txtoperator.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),0).toString());
        isiidpulsa.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),1).toString());
        isihargadefault.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),2).toString());
        isihargamember.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelpulsaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTextField isihargadefault;
    private javax.swing.JTextField isihargamember;
    private javax.swing.JTextField isiidpulsa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelpulsa;
    private javax.swing.JTextField txtoperator;
    // End of variables declaration//GEN-END:variables

    private void selectAll() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c=koneksidb.getkoneksi();
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select * from pulsa");
            while(r.next()){
             Object[] pulsa = new Object[4]; 
            pulsa[0]=r.getString("operator");
            pulsa[1]=r.getString("id_pulsa");
            pulsa[2]=r.getString("harga_default");
            pulsa[3]=r.getString("harga_member");
            model.addRow(pulsa);
            }
        }catch (SQLException e){
            System.out.println("terjadi error :" +e);
        }
}
}
