/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package owner;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;
import pulsa.pulsautama;
import rohmatcell.datamember;
import rohmatcell.login;
import rohmatcell.transaksi;

/**
 *
 * @author arifika
 */
public class halamanutama extends javax.swing.JFrame {

    /**
     * Creates new form halamanutama
     */
    public halamanutama(String user) {
        initComponents();
        labelUser.setText(user);
        
        ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          Calendar cal = new GregorianCalendar();
        String nolJam = "";
        String nolMenit = "";
        String nolDetik = "";
        String nolTanggal = "";
        String nolBulan = "";
        String nolTahun = "";
        // Membuat Date
        Date dt = new Date();
        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
        int nilaiJam = dt.getHours();
        int nilaiMenit = dt.getMinutes();
        int nilaiDetik = dt.getSeconds();
        int nilaiTanggal = cal.get(Calendar.DAY_OF_MONTH);
        int nilaiBulan = cal.get(Calendar.MONTH);
        
        int nilaiTahun = cal.get(Calendar.YEAR);
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilaiJam <= 9) {
          // Tambahkan "0" didepannya
          nolJam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilaiMenit <= 9) {
          // Tambahkan "0" didepannya
          nolMenit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilaiDetik <= 9) {
          // Tambahkan "0" didepannya
          nolDetik = "0";
        }
        if (nilaiTanggal<10){
            nolTanggal="0";
        }
        if ((nilaiBulan+1)<10){
            nolBulan="0";
        }
        if (nilaiTahun<10){
            nolTahun="0";
        }
        // Membuat String JAM, MENIT, DETIK
        String jam = nolJam + Integer.toString(nilaiJam);
        String menit = nolMenit + Integer.toString(nilaiMenit);
        String detik = nolDetik + Integer.toString(nilaiDetik);
        String tanggal = nolTanggal + Integer.toString(nilaiTanggal);
        String bulan = nolBulan + Integer.toString(nilaiBulan+1);
        String tahun = nolTahun + Integer.toString(nilaiTahun);
        // Menampilkan pada Layar
        tampiljam.setText(jam+":"+menit+":"+detik);
        tampiltanggal.setText(tahun+"-"+bulan+"-"+tanggal);
      }
    };
    // Timer
    new Timer(1000, taskPerformer).start();
  }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambarbackground1 = new rohmatcell.gambarbackground();
        desktop_panel = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        rekaptransaksi = new javax.swing.JButton();
        Transaksi = new javax.swing.JButton();
        pulsa = new javax.swing.JButton();
        datamember = new javax.swing.JButton();
        gambarbackground2 = new rohmatcell.gambarbackground();
        tampiltanggal = new javax.swing.JLabel();
        tampiljam = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout gambarbackground1Layout = new javax.swing.GroupLayout(gambarbackground1);
        gambarbackground1.setLayout(gambarbackground1Layout);
        gambarbackground1Layout.setHorizontalGroup(
            gambarbackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        gambarbackground1Layout.setVerticalGroup(
            gambarbackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        desktop_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktop_panel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                desktop_panelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton1.setText("keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(1110, 40, 130, 30);
        desktop_panel.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        rekaptransaksi.setText("Rekap Transaksi");
        rekaptransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekaptransaksiActionPerformed(evt);
            }
        });
        rekaptransaksi.setBounds(200, 40, 150, 30);
        desktop_panel.add(rekaptransaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Transaksi.setText("Transaksi");
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        Transaksi.setBounds(50, 40, 130, 30);
        desktop_panel.add(Transaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pulsa.setText("Pulsa");
        pulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsaActionPerformed(evt);
            }
        });
        pulsa.setBounds(380, 40, 130, 30);
        desktop_panel.add(pulsa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        datamember.setText("Data Member");
        datamember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datamemberActionPerformed(evt);
            }
        });
        datamember.setBounds(530, 40, 130, 30);
        desktop_panel.add(datamember, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gambarbackground2.setRequestFocusEnabled(false);

        tampiltanggal.setForeground(new java.awt.Color(255, 255, 255));
        tampiltanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampiltanggal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tanggal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        tampiltanggal.setVerifyInputWhenFocusTarget(false);

        tampiljam.setForeground(new java.awt.Color(255, 255, 255));
        tampiljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampiljam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jam", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        labelUser.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 18)); // NOI18N
        labelUser.setForeground(new java.awt.Color(255, 255, 255));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel2.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login : ");

        javax.swing.GroupLayout gambarbackground2Layout = new javax.swing.GroupLayout(gambarbackground2);
        gambarbackground2.setLayout(gambarbackground2Layout);
        gambarbackground2Layout.setHorizontalGroup(
            gambarbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gambarbackground2Layout.createSequentialGroup()
                .addContainerGap(779, Short.MAX_VALUE)
                .addGroup(gambarbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tampiltanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gambarbackground2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(tampiljam, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(451, 451, 451))
            .addGroup(gambarbackground2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gambarbackground2Layout.setVerticalGroup(
            gambarbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarbackground2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(gambarbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tampiltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampiljam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                .addGroup(gambarbackground2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        gambarbackground2.setBounds(0, 0, 1440, 730);
        desktop_panel.add(gambarbackground2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login panggil = new login ();
        panggil.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here: 
        String username = labelUser.getText().toString();
        transaksi panggil = new transaksi(username);
        desktop_panel.add(panggil);
        panggil.setLocation (150, 180);
        panggil.setVisible(true);
    }//GEN-LAST:event_TransaksiActionPerformed

    private void desktop_panelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_desktop_panelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_desktop_panelAncestorAdded

    private void pulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsaActionPerformed
        // TODO add your handling code here:
        pulsautama panggil = new pulsautama();
        desktop_panel.add(panggil);
        panggil.setLocation (180, 108);
        panggil.setVisible(true);
    }//GEN-LAST:event_pulsaActionPerformed

    private void rekaptransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekaptransaksiActionPerformed
        // TODO add your handling code here:
        rekaptransaksi panggil = new rekaptransaksi();
        desktop_panel.add(panggil);
        panggil.setLocation(120, 120);
        panggil.setVisible(true);
        
        
    }//GEN-LAST:event_rekaptransaksiActionPerformed

    private void datamemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datamemberActionPerformed
        // TODO add your handling code here:
        datamember panggil = new datamember();
        desktop_panel.add(panggil);
        panggil.setLocation(120, 120);
        panggil.setVisible(true);
        
    }//GEN-LAST:event_datamemberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Transaksi;
    private javax.swing.JButton datamember;
    private static javax.swing.JDesktopPane desktop_panel;
    private rohmatcell.gambarbackground gambarbackground1;
    private rohmatcell.gambarbackground gambarbackground2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JButton pulsa;
    private javax.swing.JButton rekaptransaksi;
    private javax.swing.JLabel tampiljam;
    private javax.swing.JLabel tampiltanggal;
    // End of variables declaration//GEN-END:variables
}
