/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package owner;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import owner.cetaktransaksi;
import rohmatcell.koneksidb;

/**
 *
 * @author arifika
 */
public class rekaptransaksi extends javax.swing.JInternalFrame {
private DefaultTableModel model;
private DefaultTableModel model1;
fungsiadmin.laba lab = new fungsiadmin.laba();
    /**
     * Creates new form rekaptransaksi
     */
    public rekaptransaksi() {
        initComponents();
                
        model = new DefaultTableModel();
        model.addColumn("Id Penjualan");
        model.addColumn("Nama Petugas");
        model.addColumn("Nomor Hp");
        model.addColumn("Harga Jual");
        model.addColumn("Tanggal");
        model.addColumn("Waktu Penjualan");
        tabelrekap.setModel(model);
        selectAll();
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cetaktransaksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelrekap = new javax.swing.JTable();
        jDateChooser11 = new com.toedter.calendar.JDateChooser();
        jDateChooser21 = new com.toedter.calendar.JDateChooser();
        tombolok = new javax.swing.JButton();
        isitglawal1 = new javax.swing.JLabel();
        isitglakhir1 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        isilaba = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("REKAP TRANSAKSI");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("REKAP TRANSAKSI");

        jLabel2.setText("Tanggal Awal    :");

        jLabel3.setText("Tanggal Akhir   :");

        cetaktransaksi.setText("cetak");
        cetaktransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetaktransaksiActionPerformed(evt);
            }
        });

        tabelrekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelrekap);

        tombolok.setText("OK");
        tombolok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolokActionPerformed(evt);
            }
        });

        isitglawal1.setText("    ");
        isitglawal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        isitglakhir1.setText("    ");
        isitglakhir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jLabel6.setText("Laba               :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isitglawal1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isitglakhir1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(tombolok, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser21, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(isilaba, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cetaktransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(isitglakhir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(isitglawal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolok, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(proses, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isilaba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cetaktransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetaktransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetaktransaksiActionPerformed
        // TODO add your handling code here:
        cetaktransaksi panggil = new cetaktransaksi();
        panggil.show();
        dispose();
    }//GEN-LAST:event_cetaktransaksiActionPerformed

    private void tombolokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolokActionPerformed
        // TODO add your handling code here:
        
        String tampilan = "yyyy-MM-dd";

        SimpleDateFormat format = new SimpleDateFormat(tampilan);

        String tanggal = String.valueOf(format.format(jDateChooser11.getDate()));
        String tanggal1 = String.valueOf(format.format(jDateChooser21.getDate()));
        isitglawal1.setText(tanggal);
        isitglakhir1.setText(tanggal1);

    }//GEN-LAST:event_tombolokActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        lab.laba(isilaba, isitglawal1, isitglakhir1);
        String tanggal_awal1, tanggal_akhir1 ;
        tanggal_awal1 = isitglawal1 .getText().trim();
        tanggal_akhir1 = isitglakhir1.getText().trim();
        String sql;
        sql = "select p.id_penjualan,t.nama_petugas, p.no_hp, u.harga_jual, p.tanggal,p.waktu_penjualan from penjualan p, pulsa u, petugas t where p.id_petugas = t.id_petugas and p.id_pulsa = u.id_pulsa and`tanggal` BETWEEN '"+tanggal_awal1+"' and '"+tanggal_akhir1+"'";
        for (int i=0;i<tabelrekap.getRowCount();i++){
            model.removeRow(i);
        }
        
        try {
            Statement statement = koneksidb.getkoneksi().createStatement();
            statement.executeQuery (sql);
            selectAll();
            
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Mengambil");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Mengambil");
        }
                                                
    }//GEN-LAST:event_prosesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetaktransaksi;
    private javax.swing.JTextField isilaba;
    private javax.swing.JLabel isitglakhir1;
    private javax.swing.JLabel isitglawal1;
    private com.toedter.calendar.JDateChooser jDateChooser11;
    private com.toedter.calendar.JDateChooser jDateChooser21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    private javax.swing.JTable tabelrekap;
    private javax.swing.JButton tombolok;
    // End of variables declaration//GEN-END:variables

    private void selectAll() {
        String tanggal_awal, tanggal_akhir ;
        tanggal_awal = isitglawal1 .getText().trim();
        tanggal_akhir = isitglakhir1.getText().trim();
        String sql;
        sql = "select p.id_penjualan,t.nama_petugas, p.no_hp, u.harga_jual, p.tanggal,p.waktu_penjualan from penjualan p, pulsa u, petugas t where p.id_petugas = t.id_petugas and p.id_pulsa = u.id_pulsa and`tanggal` BETWEEN '"+tanggal_awal+"' and '"+tanggal_akhir+"'";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c=koneksidb.getkoneksi();
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery(sql);
            while(r.next()){
                Object[] transaksi = new Object[6]; 
            transaksi[0]=r.getString("id_penjualan");
            transaksi[1]=r.getString("nama_petugas");
            transaksi[2]=r.getString("no_hp");
            transaksi[3]=r.getString("harga_jual");
            transaksi[4]=r.getString("tanggal");
            transaksi[5]=r.getString("waktu_penjualan");
            model.addRow(transaksi);
            }
        }catch (SQLException e){
            System.out.println("terjadi error :" +e);
        }
    }
}
