/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pulsa;


import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.SQLException;
import java.sql.Statement;
import rohmatcell.koneksidb;

/**
 *
 * @author arifika
 */
public class pulsautama extends javax.swing.JInternalFrame {
private DefaultTableModel model;
    /**
     * Creates new form pulsautama
     */
    public pulsautama() {
        initComponents();
        
        model = new DefaultTableModel();
        model.addColumn("Operator");
        model.addColumn("Id Pulsa");
        model.addColumn("Harga Default");
        model.addColumn("Harga Jual");
        model.addColumn("Harga Member");
        tabelpulsa.setModel(model);
        selectAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Hapus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        txtoperator = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        isihargadefault = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isihargajual = new javax.swing.JTextField();
        isihargamember = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isiidpulsa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpulsa = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PULSA");
        setAutoscrolls(true);
        setOpaque(true);
        setVisible(false);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("ID PULSA");

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        txtoperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoperatorActionPerformed(evt);
            }
        });

        jLabel2.setText("OPERATOR");

        jLabel6.setText("HARGA JUAL");

        jLabel5.setText("HARGA DEFAULT  ");

        jLabel7.setText("HARGA MEMBER");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("PULSA");

        tabelpulsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelpulsa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelpulsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpulsaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpulsa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isiidpulsa)
                            .addComponent(txtoperator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(isihargadefault)
                    .addComponent(isihargajual)
                    .addComponent(isihargamember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Hapus)
                        .addGap(18, 18, 18)
                        .addComponent(batal)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtoperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiidpulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(isihargadefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(isihargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(isihargamember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(Hapus)
                    .addComponent(batal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String operator, id_pulsa, harga_default, harga_jual, harga_member ;
        operator = txtoperator .getText().trim();
        id_pulsa = isiidpulsa.getText().trim();
        harga_default = isihargadefault.getText().trim();
        harga_jual = isihargajual.getText().trim();
        harga_member = isihargamember.getText().trim();
  
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate( "insert into pulsa values('"+operator+"','"+id_pulsa+"','"+harga_default+"','"+harga_jual+"','"+harga_member+"'))));");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
      txtoperator.setText("");
      isiidpulsa.setText("");
      isihargadefault.setText("");
      isihargajual.setText("");
      isihargamember.setText("");
    }//GEN-LAST:event_batalActionPerformed

    private void txtoperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoperatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoperatorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String operator, id_pulsa, harga_default, harga_jual, harga_member ;
        operator = txtoperator .getText().trim();
        id_pulsa = isiidpulsa.getText().trim();
        harga_default = isihargadefault.getText().trim();
        harga_jual = isihargajual.getText().trim();
        harga_member = isihargamember.getText().trim();
        
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate("UPDATE  `rohmatcell`.`pulsa` SET  `operator` =  '"+operator+"',`harga_default` =  '"+harga_default+"',`id_pulsa` =  '"+harga_jual+"',`harga_member` =  '"+harga_member+"'WHERE  `pulsa`.`id_pulsa` =  '"+id_pulsa+"';");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        String operator, id_pulsa, harga_default, harga_jual, harga_member ;
        operator = txtoperator .getText().trim();
        id_pulsa = isiidpulsa.getText().trim();
        harga_default = isihargadefault.getText().trim();
        harga_jual = isihargajual.getText().trim();
        harga_member = isihargamember.getText().trim();
        
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate ("DELETE FROM `pulsa` WHERE`id_pulsa`='"+id_pulsa+"'");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        
    }//GEN-LAST:event_HapusActionPerformed

    private void tabelpulsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpulsaMouseClicked
        // TODO add your handling code here:
         int row = tabelpulsa.getSelectedRow();
        txtoperator.setText(tabelpulsa.getModel().getValueAt(row,0).toString());
        isiidpulsa.setText(tabelpulsa.getModel().getValueAt(row,1).toString());
        isihargadefault.setText(tabelpulsa.getModel().getValueAt(row,2).toString());
        isihargajual.setText(tabelpulsa.getModel().getValueAt(row,3).toString());
        isihargamember.setText(tabelpulsa.getModel().getValueAt(row,4).toString());
    }//GEN-LAST:event_tabelpulsaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton batal;
    private javax.swing.JTextField isihargadefault;
    private javax.swing.JTextField isihargajual;
    private javax.swing.JTextField isihargamember;
    private javax.swing.JTextField isiidpulsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelpulsa;
    private javax.swing.JTextField txtoperator;
    // End of variables declaration//GEN-END:variables

    private void selectAll() {
         //To change body of generated methods, choose Tools | Templates.
        
        tabelpulsa.setModel(model);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        
        try {
            Connection c=koneksidb.getkoneksi();
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select* from pulsa");
            while(r.next()){
                Object[] pulsa = new Object[5]; 
            pulsa[0]=r.getString("operator");
            pulsa[1]=r.getString("id_pulsa");
            pulsa[2]=r.getString("harga_default");
            pulsa[3]=r.getString("harga_jual");
            pulsa[4]=r.getString("harga_member");
            model.addRow(pulsa);
            }
        }catch (SQLException e){
            System.out.println("terjadi error :" +e);
        }
    }
    
}

