/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import rohmatcell.koneksidb;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author arifika
 */
public class pendaftaranmember extends javax.swing.JInternalFrame {
private DefaultTableModel model;
    /**
     * Creates new form pendaftaranmember
     */
    public pendaftaranmember() {
        initComponents();
        
        model = new DefaultTableModel();
       
        model.addColumn("Nomor Hp");
        model.addColumn("Nama");
        model.addColumn("Nama Konter");
        model.addColumn("Pin");
        tabelpulsa.setModel(model);
        selectAll();
        
        ActionListener taskPerformer = new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
          Calendar cal = new GregorianCalendar();
        String nolJam = "";
        String nolMenit = "";
        String nolDetik = "";
        String nolTanggal = "";
        String nolBulan = "";
        String nolTahun = "";
        // Membuat Date
        Date dt = new Date();
        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
        int nilaiJam = dt.getHours();
        int nilaiMenit = dt.getMinutes();
        int nilaiDetik = dt.getSeconds();
        int nilaiTanggal = cal.get(Calendar.DAY_OF_MONTH);
        int nilaiBulan = cal.get(Calendar.MONTH);
        
        int nilaiTahun = cal.get(Calendar.YEAR);
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilaiJam <= 9) {
          // Tambahkan "0" didepannya
          nolJam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilaiMenit <= 9) {
          // Tambahkan "0" didepannya
          nolMenit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilaiDetik <= 9) {
          // Tambahkan "0" didepannya
          nolDetik = "0";
        }
        if (nilaiTanggal<10){
            nolTanggal="0";
        }
        if ((nilaiBulan+1)<10){
            nolBulan="0";
        }
        if (nilaiTahun<10){
            nolTahun="0";
        }
        // Membuat String JAM, MENIT, DETIK
        String jam = nolJam + Integer.toString(nilaiJam);
        String menit = nolMenit + Integer.toString(nilaiMenit);
        String detik = nolDetik + Integer.toString(nilaiDetik);
        String tanggal = nolTanggal + Integer.toString(nilaiTanggal);
        String bulan = nolBulan + Integer.toString(nilaiBulan+1);
        String tahun = nolTahun + Integer.toString(nilaiTahun);
        // Menampilkan pada Layar
        
        tampiltanggal.setText(tahun+"-"+bulan+"-"+tanggal);
      }
    };
    // Timer
    new Timer(1000, taskPerformer).start();
  }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpulsa = new javax.swing.JTable();
        isinamamember = new javax.swing.JTextField();
        isinomorhp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        isinamakonter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        isipin = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        tampiltanggal = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PENDAFTARAN MEMBER");

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        jLabel4.setText("NAMA");

        tabelpulsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Hp", "Nama", "Nama Konter", "Pin"
            }
        ));
        tabelpulsa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelpulsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpulsaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpulsa);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("PENDAFTARAN MEMBER");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel3.setText("NOMOR HP");

        jLabel5.setText("NAMA KONTER");

        jLabel1.setText("PIN");

        isipin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isipinActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tampiltanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampiltanggal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        tampiltanggal.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(isinamakonter)
                                    .addComponent(isinomorhp)
                                    .addComponent(isinamamember)
                                    .addComponent(isipin, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tampiltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tampiltanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batal)
                            .addComponent(isinamamember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(isinomorhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(isinamakonter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(isipin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        isinamakonter.setText("");
        isinomorhp.setText("");
        isinamamember.setText("");
        isipin.setText("");
        
    }//GEN-LAST:event_batalActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String NO_HP_MEMBER, NAMA_MEMBER, NAMA_KONTER, PIN;
        NO_HP_MEMBER = isinomorhp .getText().trim();
        NAMA_MEMBER = isinamamember .getText().trim();
        NAMA_KONTER = isinamakonter .getText().trim();
        PIN = isipin.getText().trim();
        
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate("UPDATE  `rohmatcell`.`member` SET  `NAMA_MEMBER` =  '"+NAMA_MEMBER+"',`NAMA_KONTER` =  '"+NAMA_KONTER+"',`PIN` =  '"+PIN+"' WHERE  `member`.`NO_HP_MEMBER` =  '"+NO_HP_MEMBER+"';");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        
    }//GEN-LAST:event_editActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String NO_HP_MEMBER, NAMA_MEMBER, NAMA_KONTER, PIN;
        NO_HP_MEMBER = isinomorhp .getText().trim();
        NAMA_MEMBER = isinamamember .getText().trim();
        NAMA_KONTER = isinamakonter .getText().trim();
        PIN = isipin.getText().trim();
        String b = tampiltanggal.getText().toString();    
        
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate ("INSERT INTO `member`(`NO_HP_MEMBER`, `NAMA_MEMBER`, `NAMA_KONTER`, `PIN`, `tanggal_aktif`) values('"+NO_HP_MEMBER+"','"+NAMA_MEMBER+"','"+NAMA_KONTER+"','"+PIN+"','"+b+"')");
        statement.executeUpdate ("INSERT INTO `petugas`(`ID_PETUGAS`, `ID_JABATAN`, `NAMA_PETUGAS`, `PIN`) VALUES ('"+NO_HP_MEMBER+"','1237','"+NAMA_MEMBER+"','"+PIN+"')");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
                                            
    }//GEN-LAST:event_tambahActionPerformed

    private void isipinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isipinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isipinActionPerformed

    private void tabelpulsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpulsaMouseClicked
        // TODO add your handling code here:
        int row = tabelpulsa.getSelectedRow();
        isinomorhp.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),0).toString());
        isinamamember.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),1).toString());
        isinamakonter.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),2).toString());
        isipin.setText(tabelpulsa.getModel().getValueAt(tabelpulsa.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelpulsaMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
          String NO_HP_MEMBER, NAMA_MEMBER, NAMA_KONTER, PIN;
        NO_HP_MEMBER = isinomorhp .getText().trim();
        NAMA_MEMBER = isinamamember .getText().trim();
        NAMA_KONTER = isinamakonter .getText().trim();
        PIN = isipin.getText().trim();
        
        try {
        Statement statement = koneksidb.getkoneksi().createStatement();
        statement.executeUpdate ("DELETE FROM `MEMBER` WHERE`NO_HP_MEMBER`='"+NO_HP_MEMBER+"'");
        statement.close();
        selectAll();
        //memanggil refresh agar data yang dimasukan langsung tampil
        JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        
        catch(SQLException ex){
      //  Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        
    }//GEN-LAST:event_hapusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField isinamakonter;
    private javax.swing.JTextField isinamamember;
    private javax.swing.JTextField isinomorhp;
    private javax.swing.JTextField isipin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelpulsa;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel tampiltanggal;
    // End of variables declaration//GEN-END:variables

    private void selectAll() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c=koneksidb.getkoneksi();
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery("select * from member");
            while(r.next()){
                Object[] pulsa = new Object[4]; 
            pulsa[0]=r.getString("no_hp_member");
            pulsa[1]=r.getString("nama_member");
            pulsa[2]=r.getString("nama_konter");
            pulsa[3]=r.getString("pin");
            model.addRow(pulsa);
            }
        }catch (SQLException e){
            System.out.println("terjadi error :" +e);
        }
    }
}

